#!/bin/bash
set -e

cargo fmt --all -- --check
cargo clippy --all-features --all-targets -- -D warnings
cargo test

cd infrastructure
tofu fmt -check -recursive
cd environments/staging
tofu validate
cd ../production
tofu validate
